version: '3.8'

services:
  vote:
    build: ./vote
    container_name: vote
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - voting

  result:
    build: ./result
    container_name: result
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - voting

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - voting

  worker:
    build: ./worker
    container_name: worker
    depends_on:
      - redis
      - db
    networks:
      - voting

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voting
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - voting

volumes:
  db_data:

networks:
  voting: