# Sử dụng image PostgreSQL chính thức
FROM postgres:latest

# Mở cổng 5432
EXPOSE 5432

# Thiết lập biến môi trường (tùy chọn)
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=mydb