version: '3.8'

services:
  flask1:
    build: ./flask_app
    container_name: flask1
    networks:
      - flask_network

  flask2:
    build: ./flask_app
    container_name: flask2
    networks:
      - flask_network

  nginx:
    build: ./nginx_config
    container_name: nginx_lb
    ports:
      - "8080:8080"
    depends_on:
      - flask1
      - flask2
    networks:
      - flask_network

networks:
  flask_network: